{% set version = "1.0.2" %}

package:
  name: spt3g
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/spt3g/spt3g-{{ version }}.tar.gz
  sha256: e4c16193fd2fb27238a3bf7cd895bb7abd36e159b4887fc6885a49766c712813

build:
  number: 1
  skip: true  # [win]
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - ninja
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - libpython
    - pip
    - pybind11
    - setuptools
    - setuptools-scm
    - numpy
    - libflac
    - libogg
    - libnetcdf
    - zlib
    - bzip2
    - liblzma-devel
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  run:
    - python
    - numpy
    - scipy
    - astropy-base
    - healpy

test:
  imports:
    - spt3g.core  # [build_platform == target_platform]

about:
  home: https://github.com/CMB-S4/spt3g_software
  summary: Public Subset of Analysis Software Developed by the SPT-3G Collaboration
  description: |
    This repository contains the public portions of the analysis software developed
    by the SPT-3G collaboration. It includes the IO libraries, data acquisition code
    for McGill's DfMux readout boards, pipeline glue code, a binned map-maker, and a
    sky mock-observer, as well as defining all the APIs used by the project.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://cmb-s4.github.io/spt3g_software/
  dev_url: https://github.com/CMB-S4/spt3g_software

extra:
  recipe-maintainers:
    - tskisner
    - iparask
    - arahlin
